//! Per-type bridge from [`Readable`] / [`Writable`] into the optics traits.
//!
//! `dioxus-optics` sits below `dioxus-signals` in the crate graph, so the
//! impls that expose each reactive carrier as an optic accessor live here.
//! Rust's orphan rule forbids a blanket `impl<R: Readable> Access for R` in
//! this crate (both traits are foreign from one another's perspective), so
//! every concrete `Readable` / `Writable` type gets an explicit impl — all
//! generated by the `bridge_access!` and `bridge_access_mut!` macros below.

use dioxus_optics::{
    Access, AccessMut, Combinator, HasSubscriptionTree, LensOp, Optic, PathBuffer, Pathed, RefOp,
    Subscribed, SubscriptionTree, ValueAccess,
};
use generational_box::{AnyStorage, BorrowError, BorrowMutError, Storage, WriteLock};

use crate::{
    BoxedSignalStorage, CopyValue, MappedMutSignal, MappedSignal, Memo, ReadSignal, Readable,
    ReadableRef, Signal, SignalData, Writable, WritableRef, WriteSignal,
};

/// Generate `Access` + `ValueAccess` + empty `Pathed` for a type already
/// implementing `Readable`. Roots contribute no path segments — the segments
/// accrue as optic ops wrap the root.
macro_rules! bridge_access {
    (
        impl[$($generics:tt)*] Access for $ty:ty
        where $($bounds:tt)*
    ) => {
        impl<$($generics)*> Access for $ty where $($bounds)* {
            type Target = <$ty as Readable>::Target;
            type Storage = <$ty as Readable>::Storage;

            fn try_read(
                &self,
            ) -> Option<<Self::Storage as AnyStorage>::Ref<'static, Self::Target>> {
                <Self as Readable>::try_read_unchecked(self).ok()
            }

            fn try_peek(
                &self,
            ) -> Option<<Self::Storage as AnyStorage>::Ref<'static, Self::Target>> {
                <Self as Readable>::try_peek_unchecked(self).ok()
            }
        }

        impl<$($generics)*> ValueAccess<<$ty as Readable>::Target> for $ty
        where
            $($bounds)*
            <$ty as Readable>::Target: Clone,
        {
            fn value(&self) -> <$ty as Readable>::Target {
                <Self as Readable>::try_read_unchecked(self)
                    .expect("optics: carrier read failed")
                    .clone()
            }
        }

        impl<$($generics)*> Pathed for $ty where $($bounds)* {
            fn visit_path(&self, _sink: &mut PathBuffer) {}
        }
    };
}

/// Generate `AccessMut` for a type already implementing `Writable`.
///
/// The bridge maps `AccessMut::try_write_silent` to `Writable::try_write_silent`
/// so carriers that eagerly mark_dirty on `try_write_unchecked` (SelectorScope,
/// Store) expose a path-silent write path through the optics layer.
macro_rules! bridge_access_mut {
    (
        impl[$($generics:tt)*] AccessMut for $ty:ty
        where $($bounds:tt)*
    ) => {
        impl<$($generics)*> AccessMut for $ty where $($bounds)* {
            type WriteMetadata = <$ty as Writable>::WriteMetadata;

            fn try_write(
                &self,
            ) -> Option<WriteLock<'static, Self::Target, Self::Storage, Self::WriteMetadata>> {
                <Self as Writable>::try_write_unchecked(self).ok()
            }

            fn try_write_silent(
                &self,
            ) -> Option<WriteLock<'static, Self::Target, Self::Storage, Self::WriteMetadata>> {
                <Self as Writable>::try_write_silent(self).ok()
            }
        }
    };
}

// CopyValue -----------------------------------------------------------------

bridge_access! {
    impl[T: 'static, S: Storage<T>] Access for CopyValue<T, S>
    where
}

bridge_access_mut! {
    impl[T: 'static, S: Storage<T>] AccessMut for CopyValue<T, S>
    where
}

// Signal --------------------------------------------------------------------

bridge_access! {
    impl[T: 'static, S: Storage<SignalData<T>>] Access for Signal<T, S>
    where
}

bridge_access_mut! {
    impl[T: 'static, S: Storage<SignalData<T>>] AccessMut for Signal<T, S>
    where
}

// Memo ----------------------------------------------------------------------

bridge_access! {
    impl[T: 'static + PartialEq] Access for Memo<T>
    where
}

bridge_access_mut! {
    impl[T: 'static + PartialEq] AccessMut for Memo<T>
    where
}

// ReadSignal / WriteSignal --------------------------------------------------

bridge_access! {
    impl[T: 'static, S: BoxedSignalStorage<T>] Access for ReadSignal<T, S>
    where
}

bridge_access! {
    impl[T: 'static, S: BoxedSignalStorage<T>] Access for WriteSignal<T, S>
    where
}

bridge_access_mut! {
    impl[T: 'static, S: BoxedSignalStorage<T>] AccessMut for WriteSignal<T, S>
    where
}

// MappedSignal / MappedMutSignal --------------------------------------------

bridge_access! {
    impl[V, O: 'static, F] Access for MappedSignal<O, V, F>
    where
        V: Readable,
        V::Target: 'static,
        F: Fn(&V::Target) -> &O,
}

bridge_access! {
    impl[V, O: 'static, F, FMut] Access for MappedMutSignal<O, V, F, FMut>
    where
        V: Readable,
        V::Target: 'static,
        F: Fn(&V::Target) -> &O,
}

bridge_access_mut! {
    impl[V, O: 'static, F, FMut] AccessMut for MappedMutSignal<O, V, F, FMut>
    where
        V: Writable,
        V::Target: 'static,
        F: Fn(&V::Target) -> &O,
        FMut: Fn(&mut V::Target) -> &mut O,
}

// BoxWriteMetadata is crate-private; no optics impl needed externally.

// ---------------------------------------------------------------------------
// Combinator<A, LensOp<S, U>> / Combinator<A, RefOp<S, U>> as Readable/Writable
// ---------------------------------------------------------------------------
//
// The stores derive macro emits Combinator-backed lenses (instead of
// MappedMutSignal-backed ones). For those to drop into `Store<T, Lens>`, the
// Combinator chain has to satisfy `Readable` (and, for write-capable lenses,
// `Writable`). The trait is local to this crate, so an `impl ... for
// Combinator<...>` is allowed despite Combinator being foreign.

impl<A, S, U> Readable for Combinator<A, LensOp<S, U>>
where
    A: Readable<Target = S>,
    S: 'static,
    U: 'static,
{
    type Target = U;
    type Storage = A::Storage;

    fn try_read_unchecked(&self) -> Result<ReadableRef<'static, Self>, BorrowError> {
        let parent = <A as Readable>::try_read_unchecked(self.parent())?;
        Ok(<A::Storage as AnyStorage>::map(parent, self.op().read_fn()))
    }

    fn try_peek_unchecked(&self) -> Result<ReadableRef<'static, Self>, BorrowError> {
        let parent = <A as Readable>::try_peek_unchecked(self.parent())?;
        Ok(<A::Storage as AnyStorage>::map(parent, self.op().read_fn()))
    }

    fn subscribers(&self) -> dioxus_core::Subscribers {
        <A as Readable>::subscribers(self.parent())
    }
}

impl<A, S, U> Writable for Combinator<A, LensOp<S, U>>
where
    A: Writable<Target = S>,
    S: 'static,
    U: 'static,
{
    type WriteMetadata = <A as Writable>::WriteMetadata;

    fn try_write_unchecked(&self) -> Result<WritableRef<'static, Self>, BorrowMutError> {
        let parent = <A as Writable>::try_write_unchecked(self.parent())?;
        Ok(WriteLock::map(parent, self.op().write_fn()))
    }

    fn try_write_silent(&self) -> Result<WritableRef<'static, Self>, BorrowMutError> {
        let parent = <A as Writable>::try_write_silent(self.parent())?;
        Ok(WriteLock::map(parent, self.op().write_fn()))
    }
}

impl<A, S, U> Readable for Combinator<A, RefOp<S, U>>
where
    A: Readable<Target = S>,
    S: 'static,
    U: 'static,
{
    type Target = U;
    type Storage = A::Storage;

    fn try_read_unchecked(&self) -> Result<ReadableRef<'static, Self>, BorrowError> {
        let parent = <A as Readable>::try_read_unchecked(self.parent())?;
        Ok(<A::Storage as AnyStorage>::map(parent, self.op().read_fn()))
    }

    fn try_peek_unchecked(&self) -> Result<ReadableRef<'static, Self>, BorrowError> {
        let parent = <A as Readable>::try_peek_unchecked(self.parent())?;
        Ok(<A::Storage as AnyStorage>::map(parent, self.op().read_fn()))
    }

    fn subscribers(&self) -> dioxus_core::Subscribers {
        <A as Readable>::subscribers(self.parent())
    }
}

// ---------------------------------------------------------------------------
// Optic<A, Path> as Readable/Writable
// ---------------------------------------------------------------------------
//
// Optic is a thin wrapper around an Access carrier. By also implementing
// Readable/Writable (delegating to the inner A), any Optic-shaped chain can
// slot into APIs that ask for a `Readable<Target = T>` lens — notably
// `Store::from_lens(...)`, which is what the `#[derive(Store)]` macro uses to
// turn field projections back into a `Store<F, _>` no matter what the root
// carrier was (Store, Signal, Memo, Optic, etc.).

impl<A, Path> Readable for Optic<A, Path>
where
    A: Readable,
    A::Target: 'static,
{
    type Target = A::Target;
    type Storage = A::Storage;

    fn try_read_unchecked(&self) -> Result<ReadableRef<'static, Self>, BorrowError> {
        <A as Readable>::try_read_unchecked(self.access())
    }

    fn try_peek_unchecked(&self) -> Result<ReadableRef<'static, Self>, BorrowError> {
        <A as Readable>::try_peek_unchecked(self.access())
    }

    fn subscribers(&self) -> dioxus_core::Subscribers {
        <A as Readable>::subscribers(self.access())
    }
}

impl<A, Path> Writable for Optic<A, Path>
where
    A: Writable,
    A::Target: 'static,
{
    type WriteMetadata = <A as Writable>::WriteMetadata;

    fn try_write_unchecked(&self) -> Result<WritableRef<'static, Self>, BorrowMutError> {
        <A as Writable>::try_write_unchecked(self.access())
    }

    fn try_write_silent(&self) -> Result<WritableRef<'static, Self>, BorrowMutError> {
        <A as Writable>::try_write_silent(self.access())
    }
}

// ---------------------------------------------------------------------------
// Subscribed<A> as Readable/Writable
// ---------------------------------------------------------------------------
//
// `Subscribed<A>` is the path-granular wrapper the derive macro puts around
// every field projection. To let chains produced by the macro slot into the
// existing Readable/Writable API (and all the ReadableExt helpers like
// `.cloned()` / `.set()`), we forward Readable/Writable through Subscribed
// with the same path-tracking semantics its `Access` impl already has.
//
// Reads subscribe the current ReactiveContext at the carrier's path with
// deep depth (descendant writes also fire this subscriber), and then peek —
// *not* read — the inner carrier so we don't double-subscribe to the root.

impl<A> Readable for Subscribed<A>
where
    A: Readable + Pathed,
    A::Target: 'static,
{
    type Target = A::Target;
    type Storage = A::Storage;

    fn try_read_unchecked(&self) -> Result<ReadableRef<'static, Self>, BorrowError> {
        <A as Readable>::try_peek_unchecked(self.inner()).map(|r| {
            // Path-granular subscribe (deep) instead of going through the
            // inner root's reactive context.
            let subs = self.tree().deep_subscribers(self.path().segments());
            if let Some(rc) = dioxus_core::ReactiveContext::current() {
                rc.subscribe(subs);
            }
            r
        })
    }

    fn try_peek_unchecked(&self) -> Result<ReadableRef<'static, Self>, BorrowError> {
        <A as Readable>::try_peek_unchecked(self.inner())
    }

    fn subscribers(&self) -> dioxus_core::Subscribers {
        self.tree().deep_subscribers(self.path().segments())
    }
}

impl<A> Writable for Subscribed<A>
where
    A: Writable + Pathed,
    A::Target: 'static,
{
    type WriteMetadata = <A as Writable>::WriteMetadata;

    fn try_write_unchecked(&self) -> Result<WritableRef<'static, Self>, BorrowMutError> {
        // Fire path subscribers at THIS carrier's leaf path, then ask the
        // inner for a *silent* write guard — any `SelectorScope` /
        // `Store` / nested `Subscribed` below us would otherwise also
        // eagerly mark_dirty at its own (broader) path, waking every
        // sibling of this leaf. Signal/CopyValue default to fire-on-drop
        // so their `try_write_silent` is identical to `try_write_unchecked`;
        // eagerly-firing carriers override to skip their own notify.
        self.tree().notify(self.path().segments());
        <A as Writable>::try_write_silent(self.inner())
    }

    fn try_write_silent(&self) -> Result<WritableRef<'static, Self>, BorrowMutError> {
        // Chained silent write: don't fire this tree either. The outermost
        // Subscribed in the chain (the caller's `try_write_unchecked` entry
        // point) is the only layer that notifies.
        <A as Writable>::try_write_silent(self.inner())
    }
}

// ---------------------------------------------------------------------------
// HasSubscriptionTree impls for bare reactive roots.
// ---------------------------------------------------------------------------
//
// A raw `Signal<T>` / `Memo<T>` / `CopyValue<T>` / `ReadSignal<T>` /
// `WriteSignal<T>` doesn't carry its own subscription tree — these are
// flat, whole-value reactive carriers. But to make macro-emitted field
// accessors (which are bound `__A: HasSubscriptionTree`) work on raw
// signals too, we give each of these a trivial impl that constructs a
// fresh `SubscriptionTree` on demand. The caller opts into tree-backed
// reactivity by invoking the field accessor at all.

impl<T, S> HasSubscriptionTree for CopyValue<T, S>
where
    T: 'static,
    S: Storage<T>,
{
    fn subscription_tree(&self) -> SubscriptionTree {
        SubscriptionTree::new()
    }
}

impl<T, S> HasSubscriptionTree for Signal<T, S>
where
    T: 'static,
    S: Storage<SignalData<T>>,
{
    fn subscription_tree(&self) -> SubscriptionTree {
        SubscriptionTree::new()
    }
}

impl<T> HasSubscriptionTree for Memo<T>
where
    T: 'static + PartialEq,
{
    fn subscription_tree(&self) -> SubscriptionTree {
        SubscriptionTree::new()
    }
}

impl<T, S> HasSubscriptionTree for ReadSignal<T, S>
where
    T: 'static,
    S: BoxedSignalStorage<T>,
{
    fn subscription_tree(&self) -> SubscriptionTree {
        SubscriptionTree::new()
    }
}

impl<T, S> HasSubscriptionTree for WriteSignal<T, S>
where
    T: 'static,
    S: BoxedSignalStorage<T>,
{
    fn subscription_tree(&self) -> SubscriptionTree {
        SubscriptionTree::new()
    }
}

impl<V, O, F> HasSubscriptionTree for MappedSignal<O, V, F>
where
    V: Readable,
    V::Target: 'static,
    O: 'static,
    F: Fn(&V::Target) -> &O,
{
    fn subscription_tree(&self) -> SubscriptionTree {
        SubscriptionTree::new()
    }
}

impl<V, O, F, FMut> HasSubscriptionTree for MappedMutSignal<O, V, F, FMut>
where
    V: Readable,
    V::Target: 'static,
    O: 'static,
    F: Fn(&V::Target) -> &O,
{
    fn subscription_tree(&self) -> SubscriptionTree {
        SubscriptionTree::new()
    }
}
