//! Per-type bridge from [`Readable`] / [`Writable`] into the optics traits.
//!
//! `dioxus-optics` sits below `dioxus-signals` in the crate graph, so the
//! impls that expose each reactive carrier as an optic accessor live here.
//! Rust's orphan rule forbids a blanket `impl<R: Readable> Access for R` in
//! this crate (both traits are foreign from one another's perspective), so
//! every concrete `Readable` / `Writable` type gets an explicit impl — all
//! generated by the `bridge_access!` and `bridge_access_mut!` macros below.

use dioxus_optics::{Access, AccessMut, Combinator, LensOp, PathBuffer, Pathed, RefOp, ValueAccess};
use generational_box::{AnyStorage, BorrowError, BorrowMutError, Storage, WriteLock};

use crate::{
    BoxedSignalStorage, CopyValue, MappedMutSignal, MappedSignal, Memo, ReadSignal, Readable,
    ReadableRef, Signal, SignalData, Writable, WritableRef, WriteSignal,
};

/// Generate `Access` + `ValueAccess` + empty `Pathed` for a type already
/// implementing `Readable`. Roots contribute no path segments — the segments
/// accrue as optic ops wrap the root.
macro_rules! bridge_access {
    (
        impl[$($generics:tt)*] Access for $ty:ty
        where $($bounds:tt)*
    ) => {
        impl<$($generics)*> Access for $ty where $($bounds)* {
            type Target = <$ty as Readable>::Target;
            type Storage = <$ty as Readable>::Storage;

            fn try_read(
                &self,
            ) -> Option<<Self::Storage as AnyStorage>::Ref<'static, Self::Target>> {
                <Self as Readable>::try_read_unchecked(self).ok()
            }

            fn try_peek(
                &self,
            ) -> Option<<Self::Storage as AnyStorage>::Ref<'static, Self::Target>> {
                <Self as Readable>::try_peek_unchecked(self).ok()
            }
        }

        impl<$($generics)*> ValueAccess<<$ty as Readable>::Target> for $ty
        where
            $($bounds)*
            <$ty as Readable>::Target: Clone,
        {
            fn value(&self) -> <$ty as Readable>::Target {
                <Self as Readable>::try_read_unchecked(self)
                    .expect("optics: carrier read failed")
                    .clone()
            }
        }

        impl<$($generics)*> Pathed for $ty where $($bounds)* {
            fn visit_path(&self, _sink: &mut PathBuffer) {}
        }
    };
}

/// Generate `AccessMut` for a type already implementing `Writable`.
macro_rules! bridge_access_mut {
    (
        impl[$($generics:tt)*] AccessMut for $ty:ty
        where $($bounds:tt)*
    ) => {
        impl<$($generics)*> AccessMut for $ty where $($bounds)* {
            type WriteMetadata = <$ty as Writable>::WriteMetadata;

            fn try_write(
                &self,
            ) -> Option<WriteLock<'static, Self::Target, Self::Storage, Self::WriteMetadata>> {
                <Self as Writable>::try_write_unchecked(self).ok()
            }
        }
    };
}

// CopyValue -----------------------------------------------------------------

bridge_access! {
    impl[T: 'static, S: Storage<T>] Access for CopyValue<T, S>
    where
}

bridge_access_mut! {
    impl[T: 'static, S: Storage<T>] AccessMut for CopyValue<T, S>
    where
}

// Signal --------------------------------------------------------------------

bridge_access! {
    impl[T: 'static, S: Storage<SignalData<T>>] Access for Signal<T, S>
    where
}

bridge_access_mut! {
    impl[T: 'static, S: Storage<SignalData<T>>] AccessMut for Signal<T, S>
    where
}

// Memo ----------------------------------------------------------------------

bridge_access! {
    impl[T: 'static + PartialEq] Access for Memo<T>
    where
}

bridge_access_mut! {
    impl[T: 'static + PartialEq] AccessMut for Memo<T>
    where
}

// ReadSignal / WriteSignal --------------------------------------------------

bridge_access! {
    impl[T: 'static, S: BoxedSignalStorage<T>] Access for ReadSignal<T, S>
    where
}

bridge_access! {
    impl[T: 'static, S: BoxedSignalStorage<T>] Access for WriteSignal<T, S>
    where
}

bridge_access_mut! {
    impl[T: 'static, S: BoxedSignalStorage<T>] AccessMut for WriteSignal<T, S>
    where
}

// MappedSignal / MappedMutSignal --------------------------------------------

bridge_access! {
    impl[V, O: 'static, F] Access for MappedSignal<O, V, F>
    where
        V: Readable,
        V::Target: 'static,
        F: Fn(&V::Target) -> &O,
}

bridge_access! {
    impl[V, O: 'static, F, FMut] Access for MappedMutSignal<O, V, F, FMut>
    where
        V: Readable,
        V::Target: 'static,
        F: Fn(&V::Target) -> &O,
}

bridge_access_mut! {
    impl[V, O: 'static, F, FMut] AccessMut for MappedMutSignal<O, V, F, FMut>
    where
        V: Writable,
        V::Target: 'static,
        F: Fn(&V::Target) -> &O,
        FMut: Fn(&mut V::Target) -> &mut O,
}

// BoxWriteMetadata is crate-private; no optics impl needed externally.

// ---------------------------------------------------------------------------
// Combinator<A, LensOp<S, U>> / Combinator<A, RefOp<S, U>> as Readable/Writable
// ---------------------------------------------------------------------------
//
// The stores derive macro emits Combinator-backed lenses (instead of
// MappedMutSignal-backed ones). For those to drop into `Store<T, Lens>`, the
// Combinator chain has to satisfy `Readable` (and, for write-capable lenses,
// `Writable`). The trait is local to this crate, so an `impl ... for
// Combinator<...>` is allowed despite Combinator being foreign.

impl<A, S, U> Readable for Combinator<A, LensOp<S, U>>
where
    A: Readable<Target = S>,
    S: 'static,
    U: 'static,
{
    type Target = U;
    type Storage = A::Storage;

    fn try_read_unchecked(
        &self,
    ) -> Result<ReadableRef<'static, Self>, BorrowError> {
        let parent = <A as Readable>::try_read_unchecked(self.parent())?;
        Ok(<A::Storage as AnyStorage>::map(parent, self.op().read_fn()))
    }

    fn try_peek_unchecked(
        &self,
    ) -> Result<ReadableRef<'static, Self>, BorrowError> {
        let parent = <A as Readable>::try_peek_unchecked(self.parent())?;
        Ok(<A::Storage as AnyStorage>::map(parent, self.op().read_fn()))
    }

    fn subscribers(&self) -> dioxus_core::Subscribers {
        <A as Readable>::subscribers(self.parent())
    }
}

impl<A, S, U> Writable for Combinator<A, LensOp<S, U>>
where
    A: Writable<Target = S>,
    S: 'static,
    U: 'static,
{
    type WriteMetadata = <A as Writable>::WriteMetadata;

    fn try_write_unchecked(
        &self,
    ) -> Result<WritableRef<'static, Self>, BorrowMutError> {
        let parent = <A as Writable>::try_write_unchecked(self.parent())?;
        Ok(WriteLock::map(parent, self.op().write_fn()))
    }
}

impl<A, S, U> Readable for Combinator<A, RefOp<S, U>>
where
    A: Readable<Target = S>,
    S: 'static,
    U: 'static,
{
    type Target = U;
    type Storage = A::Storage;

    fn try_read_unchecked(
        &self,
    ) -> Result<ReadableRef<'static, Self>, BorrowError> {
        let parent = <A as Readable>::try_read_unchecked(self.parent())?;
        Ok(<A::Storage as AnyStorage>::map(parent, self.op().read_fn()))
    }

    fn try_peek_unchecked(
        &self,
    ) -> Result<ReadableRef<'static, Self>, BorrowError> {
        let parent = <A as Readable>::try_peek_unchecked(self.parent())?;
        Ok(<A::Storage as AnyStorage>::map(parent, self.op().read_fn()))
    }

    fn subscribers(&self) -> dioxus_core::Subscribers {
        <A as Readable>::subscribers(self.parent())
    }
}
