//! Per-type bridge from [`Readable`] / [`Writable`] into the optics traits.
//!
//! `dioxus-optics` sits below `dioxus-signals` in the crate graph, so the
//! impls that expose each reactive carrier as an optic accessor live here.
//! Rust's orphan rule forbids a blanket `impl<R: Readable> Access for R` in
//! this crate (both traits are foreign from one another's perspective), so
//! every concrete `Readable` / `Writable` type gets an explicit impl — all
//! generated by the `bridge_access!` and `bridge_access_mut!` macros below.

use dioxus_optics::{Access, AccessMut, PathBuffer, Pathed, ValueAccess};
use generational_box::{AnyStorage, Storage, WriteLock};

use crate::{
    BoxedSignalStorage, CopyValue, MappedMutSignal, MappedSignal, Memo, ReadSignal, Readable,
    Signal, SignalData, Writable, WriteSignal,
};

/// Generate `Access` + `ValueAccess` + empty `Pathed` for a type already
/// implementing `Readable`. Roots contribute no path segments — the segments
/// accrue as optic ops wrap the root.
macro_rules! bridge_access {
    (
        impl[$($generics:tt)*] Access for $ty:ty
        where $($bounds:tt)*
    ) => {
        impl<$($generics)*> Access for $ty where $($bounds)* {
            type Target = <$ty as Readable>::Target;
            type Storage = <$ty as Readable>::Storage;

            fn try_read(
                &self,
            ) -> Option<<Self::Storage as AnyStorage>::Ref<'static, Self::Target>> {
                <Self as Readable>::try_read_unchecked(self).ok()
            }

            fn try_peek(
                &self,
            ) -> Option<<Self::Storage as AnyStorage>::Ref<'static, Self::Target>> {
                <Self as Readable>::try_peek_unchecked(self).ok()
            }
        }

        impl<$($generics)*> ValueAccess<<$ty as Readable>::Target> for $ty
        where
            $($bounds)*
            <$ty as Readable>::Target: Clone,
        {
            fn value(&self) -> <$ty as Readable>::Target {
                <Self as Readable>::try_read_unchecked(self)
                    .expect("optics: carrier read failed")
                    .clone()
            }
        }

        impl<$($generics)*> Pathed for $ty where $($bounds)* {
            fn visit_path(&self, _sink: &mut PathBuffer) {}
        }
    };
}

/// Generate `AccessMut` for a type already implementing `Writable`.
macro_rules! bridge_access_mut {
    (
        impl[$($generics:tt)*] AccessMut for $ty:ty
        where $($bounds:tt)*
    ) => {
        impl<$($generics)*> AccessMut for $ty where $($bounds)* {
            type WriteMetadata = <$ty as Writable>::WriteMetadata;

            fn try_write(
                &self,
            ) -> Option<WriteLock<'static, Self::Target, Self::Storage, Self::WriteMetadata>> {
                <Self as Writable>::try_write_unchecked(self).ok()
            }
        }
    };
}

// CopyValue -----------------------------------------------------------------

bridge_access! {
    impl[T: 'static, S: Storage<T>] Access for CopyValue<T, S>
    where
}

bridge_access_mut! {
    impl[T: 'static, S: Storage<T>] AccessMut for CopyValue<T, S>
    where
}

// Signal --------------------------------------------------------------------

bridge_access! {
    impl[T: 'static, S: Storage<SignalData<T>>] Access for Signal<T, S>
    where
}

bridge_access_mut! {
    impl[T: 'static, S: Storage<SignalData<T>>] AccessMut for Signal<T, S>
    where
}

// Memo ----------------------------------------------------------------------

bridge_access! {
    impl[T: 'static + PartialEq] Access for Memo<T>
    where
}

bridge_access_mut! {
    impl[T: 'static + PartialEq] AccessMut for Memo<T>
    where
}

// ReadSignal / WriteSignal --------------------------------------------------

bridge_access! {
    impl[T: 'static, S: BoxedSignalStorage<T>] Access for ReadSignal<T, S>
    where
}

bridge_access! {
    impl[T: 'static, S: BoxedSignalStorage<T>] Access for WriteSignal<T, S>
    where
}

bridge_access_mut! {
    impl[T: 'static, S: BoxedSignalStorage<T>] AccessMut for WriteSignal<T, S>
    where
}

// MappedSignal / MappedMutSignal --------------------------------------------

bridge_access! {
    impl[V, O: 'static, F] Access for MappedSignal<O, V, F>
    where
        V: Readable,
        V::Target: 'static,
        F: Fn(&V::Target) -> &O,
}

bridge_access! {
    impl[V, O: 'static, F, FMut] Access for MappedMutSignal<O, V, F, FMut>
    where
        V: Readable,
        V::Target: 'static,
        F: Fn(&V::Target) -> &O,
}

bridge_access_mut! {
    impl[V, O: 'static, F, FMut] AccessMut for MappedMutSignal<O, V, F, FMut>
    where
        V: Writable,
        V::Target: 'static,
        F: Fn(&V::Target) -> &O,
        FMut: Fn(&mut V::Target) -> &mut O,
}

// BoxWriteMetadata is crate-private; no optics impl needed externally.
