use crate::{
    Config, DesktopContext, document::DesktopDocument, event_handlers::WindowCloseHandler, window,
};
use dioxus_core::view::ViewExt;
use dioxus_core::{
    ComponentBuilderOutput, ComponentFunction, Element, EventHandler, Portal, PortalProps,
    Properties, RenderTargetId, Runtime, SuperInto, VComponent, VNode, provide_context,
    schedule_update, spawn, use_hook, use_hook_with_cleanup,
};
use dioxus_document::Document;
use dioxus_history::{History, MemoryHistory};
use std::{
    cell::{Cell, RefCell},
    marker::PhantomData,
    rc::Rc,
};

/// Properties for the [`Window()`] component.
///
/// Use the `config` prop to set the initial native window configuration, the
/// `onclose` prop to handle a user-initiated close, and children to choose what
/// the window renders. Configuration is applied when the window is opened.
#[derive(Clone)]
pub struct WindowProps {
    config: Rc<RefCell<Option<Config>>>,
    onclose: Option<EventHandler<()>>,
    children: Element,
}

impl Properties for WindowProps {
    type ComponentBuilder<RenderFn, Marker> = WindowComponentBuilder<RenderFn, Marker, ()>;

    fn component_builder<RenderFn, Marker>(
        render_fn: RenderFn,
    ) -> Self::ComponentBuilder<RenderFn, Marker> {
        WindowComponentBuilder {
            render_fn,
            builder: WindowPropsBuilder {
                config: None,
                onclose: None,
                children: (),
            },
            _marker: PhantomData,
        }
    }

    fn memoize(&mut self, new: &Self) -> bool {
        self.onclose = new.onclose;
        self.children = new.children.clone();
        false
    }
}

impl<RenderFn, Marker> dioxus_core::ComponentBuilderRender<RenderFn, Marker> for WindowProps
where
    RenderFn: ComponentFunction<WindowProps, Marker>,
    Marker: 'static,
{
    fn into_vcomponent(self, render_fn: RenderFn) -> VComponent {
        <Self as Properties>::into_vcomponent(self, render_fn)
    }
}

/// A [`WindowProps`] builder that remembers the [`Window()`] component function it came from,
/// mirroring the builder generated by `#[derive(Props)]`. The `rsx!` macro starts from the
/// component function, so the field setters and `build` live on this wrapper rather than on
/// [`WindowPropsBuilder`].
#[doc(hidden)]
#[must_use]
#[allow(non_camel_case_types, non_snake_case)]
pub struct WindowComponentBuilder<RenderFn, ComponentMarker, Children> {
    render_fn: RenderFn,
    builder: WindowPropsBuilder<Children>,
    _marker: PhantomData<ComponentMarker>,
}

#[allow(missing_docs)]
impl<RenderFn, ComponentMarker, Children>
    WindowComponentBuilder<RenderFn, ComponentMarker, Children>
{
    pub fn config(self, config: Config) -> Self {
        WindowComponentBuilder {
            render_fn: self.render_fn,
            builder: self.builder.config(config),
            _marker: self._marker,
        }
    }

    pub fn onclose<Marker>(
        self,
        onclose: impl SuperInto<Option<EventHandler<()>>, Marker>,
    ) -> Self {
        WindowComponentBuilder {
            render_fn: self.render_fn,
            builder: self.builder.onclose(onclose),
            _marker: self._marker,
        }
    }
}

#[allow(missing_docs)]
impl<RenderFn, ComponentMarker> WindowComponentBuilder<RenderFn, ComponentMarker, ()> {
    pub fn children(
        self,
        children: Element,
    ) -> WindowComponentBuilder<RenderFn, ComponentMarker, Element> {
        WindowComponentBuilder {
            render_fn: self.render_fn,
            builder: self.builder.children(children),
            _marker: self._marker,
        }
    }

    pub fn build(self) -> ComponentBuilderOutput<RenderFn, WindowProps, ComponentMarker> {
        ComponentBuilderOutput::new(self.render_fn, self.builder.build())
    }
}

#[allow(missing_docs)]
impl<RenderFn, ComponentMarker> WindowComponentBuilder<RenderFn, ComponentMarker, Element> {
    pub fn build(self) -> ComponentBuilderOutput<RenderFn, WindowProps, ComponentMarker> {
        ComponentBuilderOutput::new(self.render_fn, self.builder.build())
    }
}

#[doc(hidden)]
#[allow(missing_docs)]
pub struct WindowPropsBuilder<Children> {
    config: Option<Config>,
    onclose: Option<EventHandler<()>>,
    children: Children,
}

#[allow(missing_docs)]
impl<Children> WindowPropsBuilder<Children> {
    pub fn config(mut self, config: Config) -> Self {
        self.config = Some(config);
        self
    }

    pub fn onclose<Marker>(
        mut self,
        onclose: impl SuperInto<Option<EventHandler<()>>, Marker>,
    ) -> Self {
        self.onclose = onclose.super_into();
        self
    }
}

#[allow(missing_docs)]
impl WindowPropsBuilder<()> {
    pub fn children(self, children: Element) -> WindowPropsBuilder<Element> {
        WindowPropsBuilder {
            config: self.config,
            onclose: self.onclose,
            children,
        }
    }

    pub fn build(self) -> WindowProps {
        WindowProps {
            config: Rc::new(RefCell::new(self.config)),
            onclose: self.onclose,
            children: VNode::empty(),
        }
    }
}

#[allow(missing_docs)]
impl WindowPropsBuilder<Element> {
    pub fn build(self) -> WindowProps {
        WindowProps {
            config: Rc::new(RefCell::new(self.config)),
            onclose: self.onclose,
            children: self.children,
        }
    }
}

#[derive(Clone)]
struct WindowProviders {
    context: DesktopContext,
    document: Rc<dyn Document>,
    history: Rc<dyn History>,
}

#[derive(Clone)]
struct WindowState {
    target_id: RenderTargetId,
    providers: Rc<RefCell<Option<WindowProviders>>>,
    closed: Rc<Cell<bool>>,
    onclose: Rc<RefCell<Option<EventHandler<()>>>>,
    close_handler: Rc<RefCell<Option<WindowCloseHandler>>>,
}

impl WindowState {
    fn remove_close_handler(&self) {
        let Some(handler) = self.close_handler.borrow_mut().take() else {
            return;
        };
        if let Some(providers) = self.providers.borrow().as_ref() {
            providers
                .context
                .shared
                .window_close_handlers
                .remove(handler);
        }
    }

    /// Close the underlying window. Closing drops the app-side webview and
    /// its `WryQueue`, so later render passes see the target writerless and
    /// skip its writes.
    ///
    /// Runs from the `Window` scope's drop cleanup, after its rendered subtree
    /// (the portal feeding `target_id`) has already been torn down, so the
    /// render target is empty and safe to reclaim. `try_current` is `None`
    /// during full `VirtualDom` teardown, where the whole arena is dropped
    /// anyway, so the reclaim is simply skipped.
    fn close_window(&self) {
        self.remove_close_handler();
        if let Some(providers) = self.providers.borrow_mut().take() {
            if !self.closed.get() {
                providers.context.close();
            }
        }
        if let Some(runtime) = Runtime::try_current() {
            runtime.remove_render_target(self.target_id);
        }
    }

    fn release_closed_window(&self) {
        self.remove_close_handler();
        self.providers.borrow_mut().take();
    }
}

/// Render children into a separate desktop window.
///
/// `Window` behaves like an ordinary component from the app's point of view:
/// it accepts children, can read the same context as its parent, and can update
/// in response to the same state changes. The difference is that its children
/// are displayed in their own native desktop window.
///
/// The optional `config` prop customizes the window when it is opened. The
/// optional `onclose` handler runs when the user closes the native window.
///
/// ```rust,ignore
/// use dioxus::prelude::*;
/// use dioxus::desktop::{Config, Window, WindowBuilder};
///
/// fn App() -> Element {
///     rsx! {
///         Window {
///             config: Config::new().with_window(WindowBuilder::new().with_title("Inspector")),
///             onclose: move |_| tracing::info!("inspector closed"),
///             div { "Tools" }
///         }
///     }
/// }
/// ```
#[allow(non_snake_case)]
pub fn Window(props: WindowProps) -> Element {
    let schedule_update = schedule_update();
    let state = {
        let config = props.config.clone();
        use_hook(move || {
            let runtime = Runtime::current();
            let target_id = runtime.create_render_target();
            let providers = Rc::new(RefCell::new(None));
            let closed = Rc::new(Cell::new(false));
            let onclose = Rc::new(RefCell::new(None::<EventHandler<()>>));
            let close_handler = Rc::new(RefCell::new(None));
            let pending = window()
                .new_window_for_target(target_id, config.borrow_mut().take().unwrap_or_default());
            let providers_for_task = providers.clone();
            let closed_for_task = closed.clone();
            let onclose_for_task = onclose.clone();
            let close_handler_for_task = close_handler.clone();

            spawn(async move {
                let resolved_context = pending.await;
                let window_id = resolved_context.window.id();
                let closed_for_close_handler = closed_for_task.clone();
                let schedule_update_for_close_handler = schedule_update.clone();
                let close_handler =
                    resolved_context
                        .shared
                        .window_close_handlers
                        .add(window_id, move || {
                            let was_closed = closed_for_close_handler.replace(true);
                            if !was_closed {
                                if let Some(onclose) = *onclose_for_task.borrow() {
                                    onclose.call(());
                                }
                                schedule_update_for_close_handler();
                            }
                        });

                close_handler_for_task.borrow_mut().replace(close_handler);
                providers_for_task.borrow_mut().replace(WindowProviders {
                    document: Rc::new(DesktopDocument::new(resolved_context.clone())),
                    history: Rc::new(MemoryHistory::default()),
                    context: resolved_context,
                });
                schedule_update();
            });

            WindowState {
                target_id,
                providers,
                closed,
                onclose,
                close_handler,
            }
        })
    };
    state.onclose.replace(props.onclose);

    use_hook_with_cleanup(
        {
            let state = state.clone();
            move || state
        },
        |state| {
            state.close_window();
        },
    );

    if state.closed.get() {
        state.release_closed_window();
        return VNode::empty();
    }

    let Some(providers) = state.providers.borrow().clone() else {
        return VNode::empty();
    };

    portal_element(
        state.target_id,
        context_provider_element(providers, props.children.clone()),
    )
}

#[derive(Clone)]
struct WindowContextProviderProps {
    providers: WindowProviders,
    children: Element,
}

impl Properties for WindowContextProviderProps {
    type ComponentBuilder<RenderFn, Marker> =
        WindowContextProviderComponentBuilder<RenderFn, Marker, ((), ())>;

    fn component_builder<RenderFn, Marker>(
        render_fn: RenderFn,
    ) -> Self::ComponentBuilder<RenderFn, Marker> {
        WindowContextProviderComponentBuilder {
            render_fn,
            builder: WindowContextProviderPropsBuilder {
                fields: ((), ()),
                _phantom: (),
            },
            _marker: PhantomData,
        }
    }

    fn memoize(&mut self, new: &Self) -> bool {
        self.providers = new.providers.clone();
        self.children = new.children.clone();
        false
    }
}

impl<RenderFn, Marker> dioxus_core::ComponentBuilderRender<RenderFn, Marker>
    for WindowContextProviderProps
where
    RenderFn: ComponentFunction<WindowContextProviderProps, Marker>,
    Marker: 'static,
{
    fn into_vcomponent(self, render_fn: RenderFn) -> VComponent {
        <Self as Properties>::into_vcomponent(self, render_fn)
    }
}

#[doc(hidden)]
struct WindowContextProviderPropsBuilder<TypedBuilderFields> {
    fields: TypedBuilderFields,
    _phantom: (),
}

#[doc(hidden)]
struct WindowContextProviderComponentBuilder<RenderFn, ComponentMarker, TypedBuilderFields> {
    render_fn: RenderFn,
    builder: WindowContextProviderPropsBuilder<TypedBuilderFields>,
    _marker: PhantomData<ComponentMarker>,
}

impl<RenderFn, ComponentMarker, Children>
    WindowContextProviderComponentBuilder<RenderFn, ComponentMarker, ((), Children)>
{
    fn providers(
        self,
        providers: WindowProviders,
    ) -> WindowContextProviderComponentBuilder<
        RenderFn,
        ComponentMarker,
        ((WindowProviders,), Children),
    > {
        WindowContextProviderComponentBuilder {
            render_fn: self.render_fn,
            builder: self.builder.providers(providers),
            _marker: self._marker,
        }
    }
}

impl<RenderFn, ComponentMarker, Providers>
    WindowContextProviderComponentBuilder<RenderFn, ComponentMarker, (Providers, ())>
{
    fn children(
        self,
        children: Element,
    ) -> WindowContextProviderComponentBuilder<RenderFn, ComponentMarker, (Providers, (Element,))>
    {
        WindowContextProviderComponentBuilder {
            render_fn: self.render_fn,
            builder: self.builder.children(children),
            _marker: self._marker,
        }
    }
}

impl<RenderFn, ComponentMarker>
    WindowContextProviderComponentBuilder<
        RenderFn,
        ComponentMarker,
        ((WindowProviders,), (Element,)),
    >
{
    fn build(
        self,
    ) -> ComponentBuilderOutput<RenderFn, WindowContextProviderProps, ComponentMarker> {
        ComponentBuilderOutput::new(self.render_fn, self.builder.build())
    }
}

impl<Children> WindowContextProviderPropsBuilder<((), Children)> {
    fn providers(
        self,
        providers: WindowProviders,
    ) -> WindowContextProviderPropsBuilder<((WindowProviders,), Children)> {
        let (_, children) = self.fields;
        WindowContextProviderPropsBuilder {
            fields: ((providers,), children),
            _phantom: self._phantom,
        }
    }
}

impl<Providers> WindowContextProviderPropsBuilder<(Providers, ())> {
    fn children(
        self,
        children: Element,
    ) -> WindowContextProviderPropsBuilder<(Providers, (Element,))> {
        let (providers, _) = self.fields;
        WindowContextProviderPropsBuilder {
            fields: (providers, (children,)),
            _phantom: self._phantom,
        }
    }
}

impl WindowContextProviderPropsBuilder<((WindowProviders,), (Element,))> {
    fn build(self) -> WindowContextProviderProps {
        let (providers, children) = self.fields;
        WindowContextProviderProps {
            providers: providers.0,
            children: children.0,
        }
    }
}

#[allow(non_snake_case)]
fn WindowContextProvider(props: WindowContextProviderProps) -> Element {
    provide_context(props.providers.context);
    provide_context(props.providers.document);
    provide_context(props.providers.history);
    props.children
}

fn context_provider_element(providers: WindowProviders, children: Element) -> Element {
    Element::Ok(
        <WindowContextProviderProps as Properties>::component_builder(WindowContextProvider)
            .providers(providers)
            .children(children)
            .build()
            .into_vcomponent()
            .into_vnode(),
    )
}

fn portal_element(target: RenderTargetId, children: Element) -> Element {
    Element::Ok(
        <PortalProps as Properties>::component_builder(Portal)
            .target(target)
            .children(children)
            .build()
            .into_vcomponent()
            .into_vnode(),
    )
}
