//! Router-style demo that switches between four variants of a user enum
//! through the `Prism` primitive in `dioxus-optics`.
//!
//! The whole app state is `Signal<Page>` where `Page` is a 4-variant enum.
//! Each screen reads & writes *directly* into its variant's payload via a
//! prism projection — no `if let` branches in the view code, no per-variant
//! signals, no wrapper types.
//!
//! - `Page::Home` — no payload, just a label.
//! - `Page::Profile(ProfileData)` — projected with a named `ProfilePrism`
//!   (the shape a future `#[derive(Store)]` macro would emit).
//! - `Page::Settings(Settings)` — projected via inline `fn` pointers through
//!   `map_variant_with(...)` (no prism struct required).
//! - `Page::Error(String)` — projected via another inline prism.
//!
//! Run with: `cargo run --example page_router -p dioxus-optics`.

#![allow(non_snake_case)]

use dioxus::prelude::*;
use dioxus_optics::prelude::*;

fn main() {
    dioxus::launch(app);
}

#[derive(Debug, Clone, PartialEq)]
enum Page {
    Home,
    Profile(ProfileData),
    Settings(Settings),
    Error(String),
}

#[derive(Debug, Clone, PartialEq)]
struct ProfileData {
    name: String,
    followers: u32,
}

#[derive(Debug, Clone, PartialEq)]
struct Settings {
    dark_mode: bool,
    notifications: bool,
}

// A named prism for `Page::Profile`. In production this would be generated by
// `#[derive(Prism)]` or `#[derive(Store)]`; here we spell it out so the
// mechanism is visible. `Default` is what lets `map_variant::<ProfilePrism>()`
// work without threading an instance through.
#[derive(Default, Clone)]
struct ProfilePrism;

impl Prism for ProfilePrism {
    type Source = Page;
    type Variant = ProfileData;

    fn try_ref<'a>(&self, p: &'a Page) -> Option<&'a ProfileData> {
        if let Page::Profile(x) = p { Some(x) } else { None }
    }
    fn try_mut<'a>(&self, p: &'a mut Page) -> Option<&'a mut ProfileData> {
        if let Page::Profile(x) = p { Some(x) } else { None }
    }
    fn try_into_variant(&self, p: Page) -> Option<ProfileData> {
        if let Page::Profile(x) = p { Some(x) } else { None }
    }
}

// Inline prisms for the remaining two variants — no struct required. The same
// fn pointers are passed through `map_variant_with` below.
fn settings_ref(p: &Page) -> Option<&Settings> {
    if let Page::Settings(s) = p { Some(s) } else { None }
}
fn settings_mut(p: &mut Page) -> Option<&mut Settings> {
    if let Page::Settings(s) = p { Some(s) } else { None }
}
fn settings_into(p: Page) -> Option<Settings> {
    if let Page::Settings(s) = p { Some(s) } else { None }
}

fn error_ref(p: &Page) -> Option<&String> {
    if let Page::Error(m) = p { Some(m) } else { None }
}
fn error_mut(p: &mut Page) -> Option<&mut String> {
    if let Page::Error(m) = p { Some(m) } else { None }
}
fn error_into(p: Page) -> Option<String> {
    if let Page::Error(m) = p { Some(m) } else { None }
}

// Field-level accessors for the struct payloads.
fn profile_name(p: &ProfileData) -> &String { &p.name }
fn profile_name_mut(p: &mut ProfileData) -> &mut String { &mut p.name }
fn profile_followers(p: &ProfileData) -> &u32 { &p.followers }
fn profile_followers_mut(p: &mut ProfileData) -> &mut u32 { &mut p.followers }
fn settings_dark(s: &Settings) -> &bool { &s.dark_mode }
fn settings_dark_mut(s: &mut Settings) -> &mut bool { &mut s.dark_mode }
fn settings_notifications(s: &Settings) -> &bool { &s.notifications }
fn settings_notifications_mut(s: &mut Settings) -> &mut bool { &mut s.notifications }

fn app() -> Element {
    let mut page = use_signal(|| {
        Page::Profile(ProfileData {
            name: "Alice".into(),
            followers: 42,
        })
    });
    let root = Optic::from_access(page);

    // One optic per variant. Each is Optional — the underlying prism might
    // decide the current `Page` is not that variant.
    let profile = root.clone().map_variant::<ProfilePrism>();
    let settings = root
        .clone()
        .map_variant_with(settings_ref, settings_mut, settings_into);
    let error = root.map_variant_with(error_ref, error_mut, error_into);

    // Compose one more layer: project into individual fields of each variant's
    // payload. The resulting optics read and write the root signal directly.
    let profile_name = profile
        .clone()
        .map_ref_mut(profile_name, profile_name_mut);
    let profile_followers = profile.map_ref_mut(profile_followers, profile_followers_mut);
    let dark_mode = settings
        .clone()
        .map_ref_mut(settings_dark, settings_dark_mut);
    let notifications = settings.map_ref_mut(settings_notifications, settings_notifications_mut);

    rsx! {
        style { {CSS} }
        div { class: "app",
            h1 { "dioxus-optics: prism demo" }

            nav {
                button { onclick: move |_| page.set(Page::Home), "Home" }
                button {
                    onclick: move |_| page.set(Page::Profile(ProfileData {
                        name: "Alice".into(),
                        followers: 42,
                    })),
                    "Profile"
                }
                button {
                    onclick: move |_| page.set(Page::Settings(Settings {
                        dark_mode: false,
                        notifications: true,
                    })),
                    "Settings"
                }
                button {
                    onclick: move |_| page.set(Page::Error("network down".into())),
                    "Error"
                }
            }

            // Each section is rendered only when its prism succeeds, via
            // `to_option()`. No enum match statements in the view.
            if let Some(profile) = profile_name.clone().to_option() {
                section { class: "screen",
                    h2 { "Profile" }
                    label { "Name" }
                    input {
                        r#type: "text",
                        value: "{profile.read()}",
                        oninput: move |evt| {
                            if let Some(mut w) = profile_name.write_opt() {
                                *w = evt.value();
                            }
                        },
                    }
                    p { "Followers: " b { "{profile_followers.read_opt().map(|n| *n).unwrap_or(0)}" } }
                    button {
                        onclick: move |_| {
                            if let Some(mut w) = profile_followers.write_opt() { *w += 1; }
                        },
                        "+1 follower"
                    }
                }
            }

            if dark_mode.read_opt().is_some() {
                section { class: "screen",
                    h2 { "Settings" }
                    label {
                        input {
                            r#type: "checkbox",
                            checked: *dark_mode.read_opt().unwrap(),
                            oninput: move |evt| {
                                if let Some(mut w) = dark_mode.write_opt() { *w = evt.checked(); }
                            },
                        }
                        " Dark mode"
                    }
                    label {
                        input {
                            r#type: "checkbox",
                            checked: *notifications.read_opt().unwrap(),
                            oninput: move |evt| {
                                if let Some(mut w) = notifications.write_opt() { *w = evt.checked(); }
                            },
                        }
                        " Notifications"
                    }
                }
            }

            if let Some(err) = error.clone().to_option() {
                section { class: "screen error",
                    h2 { "Error" }
                    input {
                        r#type: "text",
                        value: "{err.read()}",
                        oninput: move |evt| {
                            if let Some(mut w) = error.write_opt() { *w = evt.value(); }
                        },
                    }
                }
            }

            // A plain, prism-less read from the root signal, used purely as a
            // label. Shows that prisms coexist with whole-root access.
            {
                let current = match &*page.read() {
                    Page::Home => "home",
                    Page::Profile(_) => "profile",
                    Page::Settings(_) => "settings",
                    Page::Error(_) => "error",
                };
                rsx! { footer { "Current variant: " b { "{current}" } } }
            }
        }
    }
}

const CSS: &str = r#"
body { font-family: system-ui, sans-serif; max-width: 620px; margin: 2rem auto; padding: 0 1rem; }
.app nav { display:flex; gap:.5rem; margin-bottom:1rem; }
.app .screen { margin: 1rem 0; padding: 1rem; border: 1px solid #ddd; border-radius: 8px; }
.app .screen.error { border-color: #e33; background: #fde; }
.app h2 { margin-top: 0; }
.app label { display:block; margin:.25rem 0; }
input[type=text] { margin: 0 .5rem; padding: .25rem .5rem; }
button { margin: .25rem; padding: .25rem .75rem; }
footer { margin-top: 1.5rem; color: #666; font-size: .9rem; }
"#;
