[application]
name = "concurrent-scheduler-legacy"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Stack Triangle"

[web.watcher]
reload_html = true
watch_path = ["src"]
