use crate::{AttributeValue, RenderTargetId, Runtime, arena::ElementId};
use std::{collections::BTreeMap, rc::Rc};

/// Something that can handle the mutations that are generated by the diffing process and apply them to the Real DOM
///
/// This object provides a stack-only stream of changes for a renderer to use
/// to patch the Real DOM with the state of the VirtualDom.
///
/// These changes are specific to one subtree, so to patch multiple subtrees, you'd need to handle each set separately.
///
/// Mutations are the only link between the RealDOM and the VirtualDOM.
pub trait WriteMutations {
    /// Push the node registered to `id` onto the stack.
    fn push_id(&mut self, id: ElementId);

    /// Pop the current top node and register it to `id`.
    fn pop_id(&mut self, id: ElementId);

    /// Replace the current top node with its `index`th child.
    fn child(&mut self, index: usize);

    /// Pop and discard the current top node.
    fn pop(&mut self);

    /// Create an element and push it onto the stack.
    fn create_element(&mut self, tag: &str, ns: Option<&str>);

    /// Create a text node and push it onto the stack.
    fn create_text(&mut self, value: &str);

    /// Replace the current top node with a deep clone of itself.
    fn clone(&mut self);

    /// Append the top `m` nodes to the parent below them. Leaves the parent
    /// on the stack.
    fn append_children(&mut self, m: usize);

    /// Replace the target below the top `m` nodes with those nodes. Consumes
    /// the target and replacement nodes.
    fn replace_with(&mut self, m: usize);

    /// Insert the top `m` nodes after the anchor below them. Leaves the anchor
    /// on the stack.
    fn insert_after(&mut self, m: usize);

    /// Insert the top `m` nodes before the anchor below them. Leaves the anchor
    /// on the stack.
    fn insert_before(&mut self, m: usize);

    /// Set the value of a node's attribute.
    ///
    /// Name: The name of the attribute to set.
    /// NS: The (optional) namespace of the attribute. For instance, "style" is in the "style" namespace.
    /// Value: The value of the attribute.
    fn set_attribute(&mut self, name: &str, ns: Option<&str>, value: &AttributeValue);

    /// Set the text content of a node.
    ///
    /// Value: The textcontent of the node
    fn set_text(&mut self, value: &str);

    /// Create a new Event Listener.
    ///
    /// Name: The name of the event to listen for.
    fn add_event_listener(&mut self, name: &str);

    /// Remove an existing Event Listener.
    ///
    /// Name: The name of the event to remove.
    fn remove_event_listener(&mut self, name: &str);

    /// Remove the current top node from the DOM and consume it.
    fn remove(&mut self);
}

/// Forward through a mutable reference so writer-generic code can be
/// instantiated at `&mut dyn WriteMutations`.
impl<W: WriteMutations + ?Sized> WriteMutations for &mut W {
    fn push_id(&mut self, id: ElementId) {
        (**self).push_id(id)
    }

    fn pop_id(&mut self, id: ElementId) {
        (**self).pop_id(id)
    }

    fn child(&mut self, index: usize) {
        (**self).child(index)
    }

    fn pop(&mut self) {
        (**self).pop()
    }

    fn create_element(&mut self, tag: &str, ns: Option<&str>) {
        (**self).create_element(tag, ns)
    }

    fn create_text(&mut self, value: &str) {
        (**self).create_text(value)
    }

    fn clone(&mut self) {
        WriteMutations::clone(&mut **self)
    }

    fn append_children(&mut self, m: usize) {
        (**self).append_children(m)
    }

    fn replace_with(&mut self, m: usize) {
        (**self).replace_with(m)
    }

    fn insert_after(&mut self, m: usize) {
        (**self).insert_after(m)
    }

    fn insert_before(&mut self, m: usize) {
        (**self).insert_before(m)
    }

    fn set_attribute(&mut self, name: &str, ns: Option<&str>, value: &AttributeValue) {
        (**self).set_attribute(name, ns, value)
    }

    fn set_text(&mut self, value: &str) {
        (**self).set_text(value)
    }

    fn add_event_listener(&mut self, name: &str) {
        (**self).add_event_listener(name)
    }

    fn remove_event_listener(&mut self, name: &str) {
        (**self).remove_event_listener(name)
    }

    fn remove(&mut self) {
        (**self).remove()
    }
}

/// Push `id`, run `with_node`, then pop the node.
pub(crate) fn with_id<M: WriteMutations + ?Sized, R>(
    to: &mut M,
    id: ElementId,
    with_node: impl FnOnce(&mut M) -> R,
) -> R {
    to.push_id(id);
    let result = with_node(to);
    to.pop();
    result
}

/// Push `id` and let `consume_node` consume it.
pub(crate) fn with_consumed_id<M: WriteMutations + ?Sized, R>(
    to: &mut M,
    id: ElementId,
    consume_node: impl FnOnce(&mut M) -> R,
) -> R {
    to.push_id(id);
    consume_node(to)
}

pub(crate) fn remove_id<M: WriteMutations + ?Sized>(to: &mut M, id: ElementId) {
    with_consumed_id(to, id, WriteMutations::remove);
}

pub(crate) fn reborrow_writer<'borrow, 'writer>(
    to: &'borrow mut Option<&'writer mut (dyn WriteMutations + 'writer)>,
) -> Option<&'borrow mut (dyn WriteMutations + 'borrow)> {
    match to {
        Some(to) => Some(&mut **to),
        None => None,
    }
}

pub(crate) struct LazyScope<'a, P: FnMut(&mut dyn WriteMutations)> {
    to: &'a mut dyn WriteMutations,
    push: P,
    target: Option<(Rc<Runtime>, RenderTargetId)>,
    pushed: bool,
}

impl<'a, P: FnMut(&mut dyn WriteMutations)> LazyScope<'a, P> {
    pub(crate) fn new(to: &'a mut dyn WriteMutations, push: P) -> Self {
        Self {
            to,
            push,
            target: None,
            pushed: false,
        }
    }

    pub(crate) fn new_for_current_target(
        to: &'a mut dyn WriteMutations,
        runtime: Rc<Runtime>,
        push: P,
    ) -> Self {
        let target = runtime.current_render_target_id();
        Self {
            to,
            push,
            target: Some((runtime, target)),
            pushed: false,
        }
    }

    #[inline]
    fn ensure_pushed(&mut self) {
        let in_target = match &self.target {
            Some((runtime, target)) => runtime.current_render_target_id() == *target,
            None => true,
        };
        if !self.pushed && in_target {
            (self.push)(self.to);
            self.pushed = true;
        }
    }
}

impl<P: FnMut(&mut dyn WriteMutations)> Drop for LazyScope<'_, P> {
    fn drop(&mut self) {
        if self.pushed {
            self.to.pop();
        }
    }
}

macro_rules! forward_lazy_scope {
    ($($method:ident($($arg:ident: $arg_ty:ty),*);)*) => {
        $(
            fn $method(&mut self, $($arg: $arg_ty),*) {
                self.ensure_pushed();
                WriteMutations::$method(self.to, $($arg),*);
            }
        )*
    };
}

impl<P: FnMut(&mut dyn WriteMutations)> WriteMutations for LazyScope<'_, P> {
    forward_lazy_scope! {
        push_id(id: ElementId);
        pop_id(id: ElementId);
        child(index: usize);
        pop();
        create_element(tag: &str, ns: Option<&str>);
        create_text(value: &str);
        clone();
        append_children(m: usize);
        replace_with(m: usize);
        insert_after(m: usize);
        insert_before(m: usize);
        set_attribute(name: &str, ns: Option<&str>, value: &AttributeValue);
        set_text(value: &str);
        add_event_listener(name: &str);
        remove_event_listener(name: &str);
        remove();
    }
}

pub(crate) fn append_children_to(
    to: &mut dyn WriteMutations,
    id: ElementId,
    runtime: Rc<Runtime>,
    create_children: impl FnOnce(&mut dyn WriteMutations) -> usize,
) -> usize {
    let mut to = LazyScope::new_for_current_target(to, runtime, move |to| to.push_id(id));
    let count = create_children(&mut to);
    if count > 0 {
        to.append_children(count);
    }
    count
}

pub(crate) fn insert_before_id(
    to: &mut dyn WriteMutations,
    id: ElementId,
    runtime: Rc<Runtime>,
    create_nodes: impl FnOnce(&mut dyn WriteMutations) -> usize,
) -> usize {
    let mut to = LazyScope::new_for_current_target(to, runtime, move |to| to.push_id(id));
    let count = create_nodes(&mut to);
    if count > 0 {
        to.insert_before(count);
    }
    count
}

pub(crate) fn insert_after_id(
    to: &mut dyn WriteMutations,
    id: ElementId,
    runtime: Rc<Runtime>,
    create_nodes: impl FnOnce(&mut dyn WriteMutations) -> usize,
) -> usize {
    let mut to = LazyScope::new_for_current_target(to, runtime, move |to| to.push_id(id));
    let count = create_nodes(&mut to);
    if count > 0 {
        to.insert_after(count);
    }
    count
}

pub(crate) fn replace_id_with<M: WriteMutations + ?Sized>(
    to: &mut M,
    id: ElementId,
    create_replacements: impl FnOnce(&mut M) -> usize,
) -> usize {
    with_consumed_id(to, id, |to| {
        let count = create_replacements(to);
        if count > 0 {
            to.replace_with(count);
        } else {
            to.remove();
        }
        count
    })
}

/// A host's collection of render-target writers.
///
/// The diff routes each write to the writer for the render target it lands
/// in. Single-target hosts get this for free: every [`WriteMutations`] writer
/// is a `MultiWriter` serving [`RenderTargetId::ROOT`] and nothing else.
/// Hosts that fan out to several sinks (one webview per window, one collector
/// per portal target) implement [`Self::writer_for`] over their own writer
/// storage.
pub trait MultiWriter {
    /// The writer type serving each individual target.
    type Writer: WriteMutations;

    /// The writer for `id`, or `None` for a target with no attached host.
    ///
    /// When this returns `None`, [`TargetRouter`] drops renderer mutations for
    /// that target. Hosts should serve writers for every target they want to
    /// materialize.
    fn writer_for(&mut self, id: RenderTargetId) -> Option<&mut Self::Writer>;
}

impl<W: WriteMutations> MultiWriter for W {
    type Writer = W;

    fn writer_for(&mut self, id: RenderTargetId) -> Option<&mut W> {
        if id == RenderTargetId::ROOT {
            Some(self)
        } else {
            None
        }
    }
}

/// Holds one writer per [`RenderTargetId`].
///
/// Each target's writes land in that target's writer. Only explicitly
/// inserted targets have a writer and everything else has its mutations
/// dropped by the target router.
pub struct MultiTargetWriter<W> {
    targets: BTreeMap<RenderTargetId, W>,
}

impl<W: WriteMutations> MultiTargetWriter<W> {
    /// Create an empty writer map. Targets must be inserted explicitly.
    pub fn new() -> Self {
        Self {
            targets: Default::default(),
        }
    }

    /// Create a writer map from an existing set of target writers.
    pub fn from_targets(targets: BTreeMap<RenderTargetId, W>) -> Self {
        Self { targets }
    }

    /// Insert or replace the writer for `id`.
    pub fn insert(&mut self, id: RenderTargetId, writer: W) {
        self.targets.insert(id, writer);
    }

    /// Remove and return the writer for `id`, if present.
    pub fn take(&mut self, id: RenderTargetId) -> Option<W> {
        self.targets.remove(&id)
    }

    /// Get the writer for `id`, if present.
    pub fn get(&self, id: RenderTargetId) -> Option<&W> {
        self.targets.get(&id)
    }

    /// Iterate over the registered targets and writers.
    pub fn targets(&self) -> impl Iterator<Item = (RenderTargetId, &W)> {
        self.targets.iter().map(|(id, w)| (*id, w))
    }

    /// Return the underlying target writer map.
    pub fn into_targets(self) -> BTreeMap<RenderTargetId, W> {
        self.targets
    }
}

impl<W: WriteMutations> Default for MultiTargetWriter<W> {
    fn default() -> Self {
        Self::new()
    }
}

impl<W: WriteMutations> MultiWriter for MultiTargetWriter<W> {
    type Writer = W;

    fn writer_for(&mut self, id: RenderTargetId) -> Option<&mut W> {
        self.targets.get_mut(&id)
    }
}

/// Routes diff writes to the host's per-target writers.
///
/// On every write the router resolves the active render target from the
/// runtime (every scope carries its render target; portal scopes carry the
/// portal's target) and forwards the write to that target's writer. Writes
/// for targets the host has no writer for are dropped.
pub(crate) struct TargetRouter<'a, M: MultiWriter> {
    to: &'a mut M,
    runtime: Rc<Runtime>,
}

impl<'a, M: MultiWriter> TargetRouter<'a, M> {
    pub(crate) fn new(to: &'a mut M, runtime: Rc<Runtime>) -> Self {
        Self { to, runtime }
    }

    #[inline]
    fn current(&mut self) -> Option<&mut M::Writer> {
        self.to.writer_for(self.runtime.current_render_target_id())
    }

    #[inline]
    fn with_current(&mut self, f: impl FnOnce(&mut M::Writer)) {
        if let Some(w) = self.current() {
            f(w);
        }
    }
}

macro_rules! forward_target_router {
    ($($method:ident($($arg:ident: $arg_ty:ty),*);)*) => {
        $(
            fn $method(&mut self, $($arg: $arg_ty),*) {
                self.with_current(|w| WriteMutations::$method(w, $($arg),*));
            }
        )*
    };
}

impl<M: MultiWriter> WriteMutations for TargetRouter<'_, M> {
    forward_target_router! {
        push_id(id: ElementId);
        pop_id(id: ElementId);
        child(index: usize);
        pop();
        create_element(tag: &str, ns: Option<&str>);
        create_text(value: &str);
        clone();
        append_children(m: usize);
        replace_with(m: usize);
        insert_after(m: usize);
        insert_before(m: usize);
        set_attribute(name: &str, ns: Option<&str>, value: &AttributeValue);
        set_text(value: &str);
        add_event_listener(name: &str);
        remove_event_listener(name: &str);
        remove();
    }
}

/// A `Mutation` represents a single instruction for the renderer to use to modify the UI tree to match the state
/// of the Dioxus VirtualDom.
///
/// These edits can be serialized and sent over the network or through any interface
#[derive(Debug, PartialEq)]
pub enum Mutation {
    /// Push the node registered to an element id onto the stack.
    PushId {
        /// The renderer-local element id to read.
        id: ElementId,
    },
    /// Pop the top stack node and register it to an element id.
    PopId {
        /// The renderer-local element id to write.
        id: ElementId,
    },
    /// Replace the top stack node with its child at `index`.
    Child {
        /// The child index to select.
        index: usize,
    },
    /// Pop and discard the top stack node.
    Pop,
    /// Create an element and push it onto the stack.
    CreateElement {
        /// The element tag name.
        tag: String,
        /// The optional element namespace.
        ns: Option<String>,
    },
    /// Create a text node and push it onto the stack.
    CreateText {
        /// The text node value.
        value: String,
    },
    /// Replace the top stack node with a deep clone of itself.
    Clone,
    /// Append the top `m` nodes to the parent below them.
    AppendChildren {
        /// The number of child nodes to append.
        m: usize,
    },
    /// Replace the target below the top `m` nodes with those nodes.
    ReplaceWith {
        /// The number of replacement nodes.
        m: usize,
    },
    /// Insert the top `m` nodes after the anchor below them.
    InsertAfter {
        /// The number of inserted nodes.
        m: usize,
    },
    /// Insert the top `m` nodes before the anchor below them.
    InsertBefore {
        /// The number of inserted nodes.
        m: usize,
    },

    /// Set the value of a node's attribute.
    SetAttribute {
        /// The name of the attribute to set.
        name: String,

        /// The (optional) namespace of the attribute.
        /// For instance, "style" is in the "style" namespace.
        ns: Option<String>,

        /// The value of the attribute.
        value: AttributeValue,
    },

    /// Set the textcontent of a node.
    SetText {
        /// The textcontent of the node
        value: String,
    },

    /// Create a new Event Listener.
    NewEventListener {
        /// The name of the event to listen for.
        name: String,
    },

    /// Remove an existing Event Listener.
    RemoveEventListener {
        /// The name of the event to remove.
        name: String,
    },
    /// Remove the top stack node from the renderer tree.
    Remove,
}

/// A static list of mutations that can be applied to the DOM. Note: this list does not contain any `Any` attribute values
#[derive(Debug, PartialEq, Default)]
pub struct Mutations {
    /// Any mutations required to patch the renderer to match the layout of the VirtualDom
    pub edits: Vec<Mutation>,
}

impl WriteMutations for Mutations {
    fn push_id(&mut self, id: ElementId) {
        self.edits.push(Mutation::PushId { id })
    }

    fn pop_id(&mut self, id: ElementId) {
        self.edits.push(Mutation::PopId { id })
    }

    fn child(&mut self, index: usize) {
        self.edits.push(Mutation::Child { index })
    }

    fn pop(&mut self) {
        self.edits.push(Mutation::Pop)
    }

    fn create_element(&mut self, tag: &str, ns: Option<&str>) {
        self.edits.push(Mutation::CreateElement {
            tag: tag.to_string(),
            ns: ns.map(str::to_string),
        })
    }

    fn create_text(&mut self, value: &str) {
        self.edits.push(Mutation::CreateText {
            value: value.into(),
        })
    }

    fn clone(&mut self) {
        self.edits.push(Mutation::Clone)
    }

    fn append_children(&mut self, m: usize) {
        self.edits.push(Mutation::AppendChildren { m })
    }

    fn replace_with(&mut self, m: usize) {
        self.edits.push(Mutation::ReplaceWith { m })
    }

    fn insert_after(&mut self, m: usize) {
        self.edits.push(Mutation::InsertAfter { m })
    }

    fn insert_before(&mut self, m: usize) {
        self.edits.push(Mutation::InsertBefore { m })
    }

    fn set_attribute(&mut self, name: &str, ns: Option<&str>, value: &AttributeValue) {
        self.edits.push(Mutation::SetAttribute {
            name: name.to_string(),
            ns: ns.map(str::to_string),
            value: match value {
                AttributeValue::Text(s) => AttributeValue::Text(s.clone()),
                AttributeValue::Bool(b) => AttributeValue::Bool(*b),
                AttributeValue::Float(n) => AttributeValue::Float(*n),
                AttributeValue::Int(n) => AttributeValue::Int(*n),
                AttributeValue::None => AttributeValue::None,
                _ => panic!("Cannot serialize attribute value"),
            },
        })
    }

    fn set_text(&mut self, value: &str) {
        self.edits.push(Mutation::SetText {
            value: value.into(),
        })
    }

    fn add_event_listener(&mut self, name: &str) {
        self.edits
            .push(Mutation::NewEventListener { name: name.into() })
    }

    fn remove_event_listener(&mut self, name: &str) {
        self.edits
            .push(Mutation::RemoveEventListener { name: name.into() })
    }

    fn remove(&mut self) {
        self.edits.push(Mutation::Remove)
    }
}

/// A struct that ignores all mutations
pub struct NoOpMutations;

impl WriteMutations for NoOpMutations {
    fn push_id(&mut self, _: ElementId) {}

    fn pop_id(&mut self, _: ElementId) {}

    fn child(&mut self, _: usize) {}

    fn pop(&mut self) {}

    fn create_element(&mut self, _: &str, _: Option<&str>) {}

    fn create_text(&mut self, _: &str) {}

    fn clone(&mut self) {}

    fn append_children(&mut self, _: usize) {}

    fn replace_with(&mut self, _: usize) {}

    fn insert_after(&mut self, _: usize) {}

    fn insert_before(&mut self, _: usize) {}

    fn set_attribute(&mut self, _: &str, _: Option<&str>, _: &AttributeValue) {}

    fn set_text(&mut self, _: &str) {}

    fn add_event_listener(&mut self, _: &str) {}

    fn remove_event_listener(&mut self, _: &str) {}

    fn remove(&mut self) {}
}
