[application]
name = "concurrent-scheduler"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Fiber Triangle"

[web.watcher]
reload_html = true
watch_path = ["src"]
