FROM rust:1.58-buster

RUN apt update
RUN apt install -y libglib2.0-dev libgtk-3-dev libsoup2.4-dev libappindicator3-dev libwebkit2gtk-4.0-dev firefox-esr

RUN cargo install cargo-make --debug
RUN cargo install cargo-cache && cargo cache -a

CMD ["echo","\"base image built\""]
