//! Diffing for dynamic attributes.
//!
//! Templates keep static attributes in the packed op tape and store runtime attributes in
//! `VNode::dynamic_values`. Each dynamic attribute path points at the element that owns the
//! corresponding dynamic attribute slot. Several adjacent slots may point at the same element when
//! RSX mixes named dynamic attributes and spreads.
//!
//! Creating a template can write those slots in order because later writes naturally overwrite
//! earlier writes on the real element. Diffing needs a little more context: removing a later spread
//! can reveal an earlier dynamic attribute with the same key, or the static template attribute that
//! was loaded with the template. To preserve those "last write wins" semantics, the diff:
//!
//! 1. groups all adjacent dynamic attribute slots for the same element cursor;
//! 2. flattens the old and new slots for that element;
//! 3. reduces each side to the effective attribute for each `(name, namespace)` key, keeping the
//!    last matching attribute; and
//! 4. merges the old and new effective attribute lists to emit additions, updates, removals, and
//!    static-template fallbacks.

use core::{cmp::Ordering, iter::Peekable};

use crate::innerlude::MountId;
use crate::{
    Attribute, AttributeValue, TemplatePath, VNode, VirtualDom, WriteMutations,
    arena::{ElementLocation, MountedElementId},
    diff::template::{DynamicAttrGroup, for_each_dynamic_attr_group},
    mutations::{LazyScope, with_id},
};

/// Attribute identity as seen by renderers. Value changes do not affect the key, but namespace
/// changes do.
type AttributeKey = (&'static str, Option<&'static str>);

/// Reusable scratch for the two k-way merges in `diff_attribute_list`. Allocated once per
/// `diff_attributes` call and cleared on every merge.
#[derive(Default)]
struct AttributeDiffScratch<'a> {
    old_ranges: Vec<&'a [Attribute]>,
    old_offsets: Vec<usize>,
    new_ranges: Vec<&'a [Attribute]>,
    new_offsets: Vec<usize>,
}

impl VNode {
    pub(crate) fn diff_attributes(
        &self,
        new: &VNode,
        dom: &mut VirtualDom,
        to: &mut dyn WriteMutations,
    ) {
        let mount_id = new.unchecked_mounted_id();
        let mut scratch = AttributeDiffScratch::default();

        for_each_dynamic_attr_group(self, |attr_group| {
            let Some(idx) = attr_group.first_id() else {
                return;
            };
            // Every slot in the group is mounted to the same real element, so the first slot's id
            // is enough for all mutations generated by this group.
            let attribute_id = dom.unchecked_mounted_dyn_attr(mount_id, idx);
            self.diff_attribute_list(
                new,
                &attr_group,
                attribute_id,
                mount_id,
                &mut scratch,
                dom,
                to,
            );
        });
    }

    /// Diff all dynamic attributes that can affect one mounted element.
    ///
    /// `from` and `to_attrs` are the flattened dynamic slots for the same template cursor. They may
    /// contain duplicate keys from multiple spreads or from a spread overriding a named attribute.
    /// Before we compare sides, each side is reduced to its effective, last-written attribute per
    /// key.
    fn diff_attribute_list<'a>(
        &'a self,
        new: &'a VNode,
        attr_group: &DynamicAttrGroup<'_>,
        id: MountedElementId,
        mount: MountId,
        scratch: &mut AttributeDiffScratch<'a>,
        dom: &mut VirtualDom,
        to: &mut dyn WriteMutations,
    ) {
        let AttributeDiffScratch {
            old_ranges,
            old_offsets,
            new_ranges,
            new_offsets,
        } = scratch;
        let sort_by = Self::compare_attribute_keys;
        let mut from_iter = iter_sorted_last_wins(
            attr_group.ids().map(|idx| self.dynamic_values[idx].attrs()),
            old_ranges,
            old_offsets,
            sort_by,
        )
        .peekable();
        let mut to_iter = iter_sorted_last_wins(
            attr_group.ids().map(|idx| new.dynamic_values[idx].attrs()),
            new_ranges,
            new_offsets,
            sort_by,
        )
        .peekable();

        let element_id = id.element_id();
        let mut to = LazyScope::new(to, move |to| to.push_id(element_id));
        while let Some((key, old, new)) = Self::next_attribute_diff(&mut from_iter, &mut to_iter) {
            self.diff_dynamic_attribute(attr_group, key, id, mount, old, new, dom, &mut to);
        }
    }

    /// Merge two sorted streams of effective attributes.
    ///
    /// Each returned item contains the key plus the old and/or new attribute for that key. This is
    /// the same shape as a map diff, but it avoids building maps because the inputs are already
    /// emitted in sorted order.
    fn next_attribute_diff<'a>(
        from_iter: &mut Peekable<impl Iterator<Item = &'a Attribute>>,
        to_iter: &mut Peekable<impl Iterator<Item = &'a Attribute>>,
    ) -> Option<(AttributeKey, Option<&'a Attribute>, Option<&'a Attribute>)> {
        match (from_iter.peek().copied(), to_iter.peek().copied()) {
            (Some(from), Some(to_attr)) => match Self::compare_attribute_keys(from, to_attr) {
                Ordering::Less => {
                    from_iter.next();
                    Some((Self::attribute_key(from), Some(from), None))
                }
                Ordering::Greater => {
                    to_iter.next();
                    Some((Self::attribute_key(to_attr), None, Some(to_attr)))
                }
                Ordering::Equal => {
                    from_iter.next();
                    to_iter.next();
                    Some((Self::attribute_key(to_attr), Some(from), Some(to_attr)))
                }
            },
            (Some(from), None) => {
                from_iter.next();
                Some((Self::attribute_key(from), Some(from), None))
            }
            (None, Some(to_attr)) => {
                to_iter.next();
                Some((Self::attribute_key(to_attr), None, Some(to_attr)))
            }
            (None, None) => None,
        }
    }

    fn diff_dynamic_attribute(
        &self,
        attr_group: &DynamicAttrGroup<'_>,
        key: AttributeKey,
        id: MountedElementId,
        mount: MountId,
        old: Option<&Attribute>,
        new: Option<&Attribute>,
        dom: &mut VirtualDom,
        to: &mut dyn WriteMutations,
    ) {
        let old_listener = matches!(old.map(|a| &a.value), Some(AttributeValue::Listener(_)));
        let new_listener = matches!(new.map(|a| &a.value), Some(AttributeValue::Listener(_)));

        // Listener-to-listener: events dispatch by path and the handler in the vdom is already current.
        if old_listener && new_listener {
            return;
        }

        let value_changed = old.map(|a| &a.value) != new.map(|a| &a.value);
        let volatile = old.is_some_and(|a| a.volatile) || new.is_some_and(|a| a.volatile);
        // If the value didn't change and neither side is volatile, then there's no need to update the attribute.
        if !value_changed && !volatile {
            return;
        }

        // Clear the old slot when the upcoming write won't naturally overwrite it: listeners
        // are torn down explicitly, and installing a listener doesn't clear a prior attribute.
        match (old_listener, new_listener, old) {
            // This used to be a listener but no longer is, so remove the old listener.
            (true, _, Some(old)) => {
                to.remove_event_listener(&old.name[2..]);
            }
            // This used to be a value but is now a listener, so clear the old value that won't be overwritten by the new listener.
            (false, true, Some(_)) => {
                to.set_attribute(key.0, key.1, &AttributeValue::None);
            }
            _ => {}
        }

        // Write the new value, or restore the static template attribute, or clear the DOM
        // attribute. A removed listener has nothing attribute-shaped left to clear.
        if let Some(new) = new {
            self.write_attribute_to_current(attr_group.path(), new, id, mount, dom, to);
        } else if !old_listener {
            self.remove_attribute_or_write_fallback(attr_group, key, to)
        }
    }

    /// Get the identity key for an attribute
    fn attribute_key(attribute: &Attribute) -> AttributeKey {
        (attribute.name, attribute.namespace)
    }

    /// Compare two attributes by their key for sorting and merging purposes.
    fn compare_attribute_keys(left: &Attribute, right: &Attribute) -> Ordering {
        Self::attribute_key(left).cmp(&Self::attribute_key(right))
    }

    /// Return the contiguous run of dynamic attribute slots mounted to the same template cursor.
    ///
    /// Attribute cursors are emitted in template order, so all slots for a single element are
    /// adjacent. Grouping them here is what lets the diff handle duplicate keys across spreads.
    /// Restore the static template attribute that was shadowed by a dynamic attribute or clear the attribute.
    ///
    /// This is needed when an attribute from a spread disappears. The template load already wrote
    /// the static value during creation, but the dynamic attribute may have overwritten or removed
    /// it on a previous render.
    fn remove_attribute_or_write_fallback(
        &self,
        attr_group: &DynamicAttrGroup<'_>,
        key: AttributeKey,
        to: &mut dyn WriteMutations,
    ) {
        if let Some(value) = attr_group.static_attr_value_for_key(key) {
            let value = AttributeValue::Text(value.to_string());
            to.set_attribute(key.0, key.1, &value);
        } else {
            to.set_attribute(key.0, key.1, &AttributeValue::None);
        }
    }

    /// Write one dynamic attribute to an already mounted element.
    ///
    /// Listener attributes also need an `ElementRef` in the runtime so event dispatch can find
    /// the VNode that owns the handler.
    pub(crate) fn write_attribute(
        &self,
        cursor: TemplatePath,
        attribute: &Attribute,
        id: MountedElementId,
        mount: MountId,
        dom: &mut VirtualDom,
        to: &mut dyn WriteMutations,
    ) {
        with_id(to, id.element_id(), |to| {
            self.write_attribute_to_current(cursor, attribute, id, mount, dom, to);
        });
    }

    fn write_attribute_to_current(
        &self,
        cursor: TemplatePath,
        attribute: &Attribute,
        id: MountedElementId,
        mount: MountId,
        dom: &mut VirtualDom,
        to: &mut dyn WriteMutations,
    ) {
        match &attribute.value {
            AttributeValue::Listener(_) => {
                dom.set_element_ref_for_mount(mount, id, ElementLocation::Static(cursor));
                to.add_event_listener(&attribute.name[2..]);
            }
            _ => {
                to.set_attribute(attribute.name, attribute.namespace, &attribute.value);
            }
        }
    }
}

/// K-way merge over attribute slots that are each individually sorted by their key.
///
/// Every dynamic attribute slot is required to be sorted by `(name, namespace)`:
/// - named attributes occupy a slot of length 1 (trivially sorted), and
/// - spread attributes are user-provided lists whose sortedness is checked in `VNode::new` under
///   `debug_assertions`.
///
/// Duplicate keys across or within slots collapse to the last occurrence in iteration order,
/// which matches the "later write wins" semantics of RSX source order.
fn iter_sorted_last_wins<'items, 'scratch, T, F>(
    slots: impl IntoIterator<Item = &'items [T]>,
    ranges: &'scratch mut Vec<&'items [T]>,
    offsets: &'scratch mut Vec<usize>,
    sort_by: F,
) -> SortedRangeIter<'items, 'scratch, T, F>
where
    F: Fn(&T, &T) -> Ordering + Copy,
{
    ranges.clear();
    ranges.extend(slots);
    offsets.clear();
    offsets.resize(ranges.len(), 0);
    SortedRangeIter {
        ranges,
        offsets,
        sort_by,
    }
}

struct SortedRangeIter<'items, 'scratch, T, F> {
    ranges: &'scratch Vec<&'items [T]>,
    offsets: &'scratch mut Vec<usize>,
    sort_by: F,
}

impl<'items, T, F> Iterator for SortedRangeIter<'items, '_, T, F>
where
    F: Fn(&T, &T) -> Ordering + Copy,
{
    type Item = &'items T;

    fn next(&mut self) -> Option<Self::Item> {
        let mut min_value = None;

        // Find the smallest key currently visible across every range.
        for (range, offset) in self.ranges.iter().zip(self.offsets.iter()) {
            if let Some(item) = range.get(*offset) {
                match min_value.map(|min_value| (self.sort_by)(item, min_value)) {
                    None | Some(Ordering::Less) => min_value = Some(item),
                    Some(Ordering::Equal | Ordering::Greater) => {}
                }
            }
        }

        let min_value = min_value?;
        let mut last = None;

        // Drain that key from every matching range. Later ranges come later in RSX source order,
        // so the final item we see is the effective last-write-wins value.
        for (range_idx, range) in self.ranges.iter().enumerate() {
            while let Some(item) = range.get(self.offsets[range_idx]) {
                if !matches!((self.sort_by)(item, min_value), Ordering::Equal) {
                    break;
                }
                last = Some(item);
                self.offsets[range_idx] += 1;
            }
        }

        last
    }
}

#[test]
fn test_iter_sorted_last_wins() {
    #[derive(Debug, PartialEq)]
    struct Item {
        value: i32,
        id: usize,
    }
    impl Item {
        fn cmp(&self, other: &Self) -> Ordering {
            self.value.cmp(&other.value)
        }
    }
    // Two sorted slots that share keys. The slot listed second wins on duplicates.
    let slot_a = [
        Item { value: 1, id: 0 },
        Item { value: 2, id: 1 },
        Item { value: 3, id: 2 },
    ];
    let slot_b = [
        Item { value: 1, id: 5 },
        Item { value: 2, id: 3 },
        Item { value: 4, id: 4 },
    ];
    let mut ranges = Vec::new();
    let mut offsets = Vec::new();
    let mut iter = iter_sorted_last_wins(
        [slot_a.as_slice(), slot_b.as_slice()],
        &mut ranges,
        &mut offsets,
        Item::cmp,
    );
    assert_eq!(*iter.next().unwrap(), Item { value: 1, id: 5 });
    assert_eq!(*iter.next().unwrap(), Item { value: 2, id: 3 });
    assert_eq!(*iter.next().unwrap(), Item { value: 3, id: 2 });
    assert_eq!(*iter.next().unwrap(), Item { value: 4, id: 4 });
    assert!(iter.next().is_none());
}
