[tasks.build_ios_sim]
args = ["bundle", "--target", "aarch64-apple-ios-sim", "--features", "mobile"]
command = "cargo"

[tasks.install_ios_sim]
command = "xcrun"
args = [
  "simctl",
  "install",
  "booted",
  "target/aarch64-apple-ios-sim/debug/bundle/ios/DioxusApp.app",
]

[tasks.run_ios_sim]
env = { SIMCTL_CHILD_DIOXUS_DEVSERVER_ADDR="ws://0.0.0.0:8080/_dioxus", SIMCTL_CHILD_CARGO_MANIFEST_DIR="/Users/jonkelley/Development/Tinkering/ios-binary"}
args = ["simctl", "launch", "--console", "booted", "com.dioxuslabs"]
command = "xcrun"
dependencies = ["build_ios_sim", "install_ios_sim"]

[tasks.serve-sim]
dependencies = ["build_ios_sim", "install_ios_sim", "run_ios_sim"]

[tasks.build_ios_device]
command = "cargo"
args = ["bundle", "--target", "aarch64-apple-ios"]

[tasks.code-sign-ios-device]
command = "./tools/make-entitlements.sh"

# god bless the crypto bros <3
# https://github.com/status-im/status-mobile/blob/6a5e718cd389f61d3708c4372856609afb40d11f/scripts/run-ios-device.sh#L6
[tasks.run-ios-device]
command = "./tools/run-ios-device.sh"

[tasks.serve-device]
dependencies = [
  "build_ios_device",
  "code-sign-ios-device",
  "run-ios-device",
]

[tasks.serve]
dependencies = [
  "run_ios_sim",
]
